# Netlify redirects
# 1. To add a subdomain, add a redirect in this file first and merge the PR
# 2. Add the subdomain to the Processing website in netlify by going to Domain Management -> Production Domains -> Add domain alias

[[redirects]]
  from = "https://wiki.processing.org/*"
  to = "https://github.com/processing/processing4/wiki"
  status = 302
  force = true

[[redirects]]
  from = "https://vscode.processing.org/*"
  to = "https://marketplace.visualstudio.com/items?itemName=processing-foundation.processing-vscode-extension"
  status = 302
  force = true

[[redirects]]
  from = "https://discord.processing.org/*"
  to = "https://discord.gg/h99u95nU7q"
  status = 302
  force = true
